version: "3.3"
services:
  node:
    build: 
      context: ./docker
      dockerfile: Dockerfile_node
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
    command: sh -c "cd react-work && yarn start"
    ports:
      - "3000:3000"